plugins {
    id 'application'
}

dependencies {
    implementation testFixtures(project(':messaging-conformance'))
    implementation testFixtures(project(':messaging-jms'))
    implementation libs.junit.platform.launcher
    runtimeOnly libs.logback.classic
    runtimeOnly libs.artemis.jakarta.client
    runtimeOnly libs.ibm.mq.jakarta.client
}

application {
    mainClass = 'com.messaging.sample.SampleApp'
}
